AloTleDelisia/AloTleDelisia/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

AloTleDelisia/myapp/urls.py
from django.urls import path
from .views import index
from .views import categoria, listaRestaurantes,cerrar,restaurante,guardar_pedido,login,register_view,pedidoUsuario
from django.views.i18n import set_language

urlpatterns = [
    path('', index, name='index'),
    path('principal', categoria, name='principal'),
    path('login/', login, name='login'),
    path('cerrar-sesion/', cerrar, name='cerrar'),
    path('restaurantes/', listaRestaurantes, name='restaurantes'),
    path('restaurantes/<str:idTipoRestaurante>', listaRestaurantes, name='listaRestaurantes'),
    path('restaurante/', restaurante, name='unRestaurante'),
    path('restaurante/<str:nombreRestaurante>', restaurante, name='restaurante'),
    path('pedidos/guardar', guardar_pedido, name='guardar_pedido'),
    path('registro/',register_view , name='registro'),
    path('set_language/', set_language, name='set_language'),
    path('miPerfil/', pedidoUsuario, name='usuario')
]

AloTleDelisia/myapp/models.py
from django.db import models
from django.conf import settings



class Pedido(models.Model):
    idPedido = models.AutoField(primary_key=True)
    importePedido = models.DecimalField(max_digits=10, decimal_places=2)
    username = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    id_restaurante = models.ForeignKey('Restaurante', on_delete=models.CASCADE)

class TipoRestaurante(models.Model):
    idTipoRestaurante = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=255)


class Restaurante(models.Model):
    idRestaurante = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=255)
    ubicacion = models.CharField(max_length=255)
    horario = models.CharField(max_length=255)
    descripcion = models.TextField()
    idTipoRestaurante = models.ForeignKey(TipoRestaurante, on_delete=models.CASCADE)


class TipoProducto(models.Model):
    idTipoProducto = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=255)
    descripcion=models.TextField()
    idRestaurante = models.ForeignKey(Restaurante, on_delete=models.CASCADE)


class Producto(models.Model):
    idProducto = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=255)
    descripcionProducto = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    idTipoProducto = models.ForeignKey(TipoProducto, on_delete=models.CASCADE)
    idRestaurante = models.ForeignKey('Restaurante', on_delete=models.CASCADE)


class Menu(models.Model):
    idMenu = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField()
    idTipoProducto = models.ForeignKey(TipoProducto, on_delete=models.CASCADE)

class PedidoProducto(models.Model):
    idPedidoProducto = models.AutoField(primary_key=True)
    idPedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    idProducto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()

AloTleDelisia/myapp/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    # Agrega campos personalizados según sea necesario
    email = forms.EmailField(max_length=254)



    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

AloTleDelisia/myapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Producto, TipoRestaurante, TipoProducto, Restaurante, PedidoProducto, Pedido
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.http import JsonResponse
import json
from django.contrib.auth import authenticate, login
from django.utils import translation
from .forms import SignUpForm

def index(request):
    return render(request, 'myapp/primera.html')

def listaRestaurantes(request, idTipoRestaurante):
    tipoRestaurante = get_object_or_404(TipoRestaurante, idTipoRestaurante=idTipoRestaurante)
    restaurantes = tipoRestaurante.restaurante_set.all()

    context = {
        'tipoRestaurante': tipoRestaurante,
        'restaurantes': restaurantes,
    }

    return render(request, 'restaurantes.html', context)

def restaurante(request, nombreRestaurante):
    restaurante = get_object_or_404(Restaurante, nombre=nombreRestaurante)
    productos = Producto.objects.filter(idRestaurante=restaurante)
    categorias = TipoProducto.objects.filter(producto__idRestaurante=restaurante).distinct()

    restaurante_id = restaurante.idRestaurante

    username = request.user.username if request.user.is_authenticated else None

    context = {
        'restaurante': restaurante,
        'productos': productos,
        'categorias': categorias,
        'username': username, 
        'restaurante_id': restaurante_id,  
    }
    return render(request, 'unRestaurante.html', context)

def pedidoUsuario(request):
    usuario = request.user
    pedidosUsuario = Pedido.objects.filter(username=usuario)
    productosPedido = PedidoProducto.objects.filter(idPedido__in=pedidosUsuario)

    context = {
        'usuario': usuario,
        'pedidos': pedidosUsuario,
        'productosPedido': productosPedido,
    }
    return render(request, 'myapp/usuario.html', context)



def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password1']
        user = authenticate(request, username=username, password=password1)

        if user is not None:
            login(request, user)
            return redirect('principal')  
        else:
            return render(request, 'myapp/login.html', {'error': 'Credenciales inválidas'})

    return render(request, 'myapp/login.html')


def register_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            
            return redirect('login')
    else:
        form = SignUpForm()

    return render(request, 'registro.html', {'form': form})

def categoria(request):
    categorias = TipoRestaurante.objects.all()

    context = {'categorias': categorias}

    return render(request, 'myapp/principal.html', context)

def cerrar(request):
    logout(request)
    return redirect('index')

def guardar_pedido(request):
    if request.method == 'POST':
    
        importePedido = request.POST['importePedido']
        username = request.POST['username']
        id_restaurante = request.POST.get('id_restaurante')
        restaurante = Restaurante.objects.get(pk=id_restaurante)

        pedido = Pedido()
        pedido.importePedido = importePedido
        pedido.username = User.objects.get(username=username)
        pedido.id_restaurante = restaurante
        pedido.save()

      
        productos_json = request.POST.get('productos')

       
        productos = json.loads(productos_json)

       
        for producto in productos:
            producto_pedido = PedidoProducto()
            producto_pedido.idPedido = pedido
            producto_pedido.idProducto = Producto.objects.get(nombre=producto['titulo'])
            producto_pedido.cantidad = producto['cantidad']
            producto_pedido.save()

        return JsonResponse({'message': 'Pedido guardado exitosamente'})

    return JsonResponse({'error': 'Método no permitido'}, status=405)

def change_language(request):
    language = request.GET.get('language', 'es')  # 'en' es el idioma predeterminado

    # Cambia el idioma y actualiza la sesión
    translation.activate(language)
    request.session[translation.LANGUAGE_SESSION_KEY] = language

    # Redirige a la página desde la que se hizo la solicitud
    return redirect(request.GET.get('next', '/'))

AloTleDelisia/myapp/templates/myapp/base.html
{% load static %}

{% load i18n %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% trans "ALO TLE DELISIA - Página Principal" %} {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/stylePrincipal.css' %}">
</head>

<body>
    <div class="header-desktop">
        <div class="container">
            <div class="row d-flex align-items-center">
                <div class="col d-flex justify-content-start">
                    <button class="logo-btn-desktop">
                        <a href="{% url 'principal' %}"><img src="{% static 'imagenes/logo.png' %}" alt="LOGO"></a>
                    </button>
                </div>
                <div class="col d-flex justify-content-center">
                    <p>ALO TLE DELISIA</p>
                </div>
                <div class="col d-flex justify-content-end">
                    <button class="usuario-btn-desktop">
                        <a href={% url 'usuario' %}>
                            <img src="{% static 'imagenes/perfil.png' %}" alt="USUARIO">
                        </a>
                    </button>
                    <button class="cerrar-btn-desktop">
                        <a href="{% url 'cerrar' %}">
                            <img src="{% static 'imagenes/cerrar.png' %}" alt="CERRAR">
                        </a>
                    </button>
                </div>
                <div class="idioma">
                    <select id="languageSelect">
                        <option value="en" {% if request.LANGUAGE_CODE == 'en' %}selected{% endif %}>English</option>
                        <option value="es" {% if request.LANGUAGE_CODE == 'es' %}selected{% endif %}>Español</option>
                    </select>
                </div>
            </div>
        </div>
    </div>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="footer-content">
                        <a href="{% url 'principal' %}"><img src="{% static 'imagenes/logo.png' %}" alt="Logo"
                                class="footer-logo"></a>
                        <h4>{% trans "Colabora con nosotros"%}</h4>
                        <ul style="list-style: none; padding: 0;">
                            <li>{% trans "Trabaja con nosotros"%}</li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="footer-content">
                        <h4>{% trans "Enlaces de Interés"%}</h4>
                        <ul>
                            <li>{% trans "Acerca de nosotros"%}</li>
                            <li>{% trans "Preguntas frecuentes"%}</li>
                            <li>{% trans "Contacto"%}</li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="footer-content">
                        <h4>{% trans "Síguenos"%}</h4>
                        <ul>
                            <li>Facebook</li>
                            <li>Twitter</li>
                            <li>Instagram</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>


    <script>
        // Obtén el elemento select
        const languageSelect = document.getElementById('languageSelect');

        // Añade un evento de cambio al select
        languageSelect.addEventListener('change', function () {
            // Obtén el valor seleccionado
            const selectedLanguage = languageSelect.value;

            // Redirige a la vista con el nuevo idioma
            window.location.href = `{% url 'set_language' %}?language=${selectedLanguage}`;
        });
    </script>


</body>

</html>

AloTleDelisia/myapp/templates/myapp/chatbot.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <title>CodePen - MediaPipe Text Classifier for web</title>
  <link rel="stylesheet" href="{%static css/chatbot.css%}">

</head>

<body>
<link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">
<script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>

  <p><b>Escriba su opinión acerca del servicio ofrecido porfavor:
    </b>
  </p>
  <label class="mdc-text-field mdc-text-field--filled mdc-text-field--textarea mdc-text-field--no-label">
    <span class="mdc-text-field__ripple"></span>
    <span class="mdc-text-field__resizer">

      <textarea id="input" class="mdc-text-field__input" rows="8" cols="40" aria-label="Text Input"></textarea>
    </span>
    <span class="mdc-line-ripple"></span>
  </label></br>
  <button id="submit" class="mdc-button mdc-button--raised">
    <span class="mdc-button__label">ENVIAR</span>
  </button></br>

  <p><b>Detección de sentimientos:</b></p>
  <p id="output"></p>
</section>

  <script type="module" src="{% static js/chatbot.js%}"></script>
</body>

</html>

AloTleDelisia/myapp/templates/myapp/primera.html
{% load static %}

{% load i18n %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alo tle delisia</title>
    <link rel="stylesheet" href="{% static 'css/stylePrimera.css' %}">
</head>
<body>
    <div class="hero">
        <nav>
          <img src="{% static 'imagenes/logo.png' %}" class="logo">  <h1>Alo tle delisia</h2>
           <div>
            <a href="{% url 'login' %}" class="btn">{% trans "Empieza" %}</a>
           </div>
        </nav>
           <div class="content">
            <h1>{% trans "Comida china a domicio" %}</h1>
            <p>{% trans "Comida vegetariana, sushi, ramen y fusión" %}</p>
           </div>
           <img src="{% static 'imagenes/sushi.png' %}" class="feature-image animation">
    </div>      
</body>
</html>

AloTleDelisia/myapp/templates/myapp/principal.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    {% load static %}
	<link rel="stylesheet" href="{% static 'css/stylePrincipal.css' %}">
    <div class="main-desktop">
        <div class="container">
            <div class="row d-flex justify-content-center mt-4">
                <h1>{% trans "¿Qué te apetece comer hoy?" %}</h1>
            </div>
            <br><br><br>
            <div class="row d-flex justify-content-center">
				{% for categoria in categorias %}
				{% if categoria.idTipoRestaurante == 2 %}
				<div class="row d-flex justify-content-center">
					<div class="category-btn">
					<a href="{% url 'listaRestaurantes' idTipoRestaurante='2'%}">
						<img src="{% static 'imagenes/zanahoria.png' %}" alt="{{ categoria.nombre }}" width="65px">
						<p>{{categoria.nombre}}</p>
					</a>
					</div>
					{%endif%}
					{%endfor%}
					{% for categoria in categorias %}
					{% if categoria.idTipoRestaurante == 1 %}
					<div class="category-btn">
						<a href="{% url 'listaRestaurantes' idTipoRestaurante='1' %}">
							<img src="{% static 'imagenes/sushi1.png' %}" alt="{{ categoria.nombre }}" width="65px">
							<p>{{categoria.nombre}}</p>
						</a>
					</div>
					{%endif%}
					{%endfor%}
					{% for categoria in categorias %}
					{% if categoria.idTipoRestaurante == 3 %}
					<div class="category-btn">
						<a href="{% url 'listaRestaurantes' idTipoRestaurante='3' %}">
							<img src="{% static 'imagenes/ramen.png' %}" alt="{{ categoria.nombre }}" width="65px">
							<p>{{categoria.nombre}}</p>
						</a>
					</div>
					{%endif%}
					{%endfor%}
					{% for categoria in categorias %}
					{% if categoria.idTipoRestaurante == 4 %}
					<div class="category-btn">
						<a href="{% url 'listaRestaurantes' idTipoRestaurante='4' %}">
							<img src="{% static 'imagenes/comidaFusion.png' %}" alt="{{ categoria.nombre }}" width="65px">
							<p>{{categoria.nombre}}</p>
						</a>
					</div>
					{%endif%}
					{%endfor%}		
			</div>
		</div>
            </div>
			</div>
{% endblock %}

AloTleDelisia/myapp/templates/myapp/registro.html
{% load i18n %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% trans "Registro" %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styleRegistro.css' %}">
</head>
<body>
    <div class="cajafuera" align="center">
        <!-- <div class="imgv"/>
           <img src="{% static 'imagenes/logo.png' %}" alt="Logo"> 
        </div> -->
    
    <div class="formulariocaja">
    <h2>{% trans "Registro" %}</h2>
    <form method="post" action="{% url 'registro' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="botonenviar">Registrarse</button>
    </form>
    </div>
</body>
</html>

AloTleDelisia/myapp/templates/myapp/restaurantes.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/stylePrincipal.css' %}">
    <link rel="stylesheet" href="{% static 'css/stylerestaurantesSushi.css' %}">

    <div class="wrapper">
        <aside class="lado">
            <h2>{% trans "Restaurantes disponibles" %}</h2>
            <ul>
                {% for unRestaurante in restaurantes %}
                    <li><a href="{% url 'restaurante' unRestaurante.nombre %}" class="restaurante">{{ unRestaurante.nombre }}</a></li>
                {% endfor %}
            </ul>
        </aside>

        <main class="principal">
            <div class="primerBloque">
                <br>
                <div class="buscador">
                    <input type="text" class="buscar" id="inputBuscar" placeholder="{% trans 'Busca aquí' %}">
                    <button class="search-button" id="btnBuscar">&#128269; {% trans "Buscar" %}</button>
                </div>
            </div>
            <div class="restaurantes">
                {% for unRestaurante in restaurantes %}
                    <a href="{% url 'restaurante' unRestaurante.nombre %}" class="restaurante-link">
                        <div class="restaurante1">
                            <img src="{% static 'imagenes/' %}{{ unRestaurante.nombre|lower }}.png" alt="{{ unRestaurante.nombre }}">
                            <p>{{ unRestaurante.nombre }}</p>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </main>
    </div>
    <script src="{% static 'js/restaurante.js' %}"></script>
{% endblock %}

AloTleDelisia/myapp/templates/myapp/unRestaurante.html
{% extends 'base.html' %}

{% load i18n%}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/stylePrincipal.css' %}">
    <link rel="stylesheet" href="{% static 'css/sushiDonosti.css' %}">
    <div class="wrapper">
        <aside class="lado">
            <h2>{% trans "Secciones" %}</h2>
            <ul>
                {% for categoria in categorias %}
                    <li><a href=#{{categoria.nombre}}>{{categoria.nombre}}</a></li>
                {% endfor %}
            </ul>
        </aside>
        <div class="main">
            <div class="primerBloque">
                <h1 class="restaurante">{{ restaurante.nombre }}</h1>
                <br>
                <div class="buscador">
                    <input type="text" class="buscar" placeholder="{% trans 'Busca aquí' %}">
                    <button class="search-button">&#128269; {% trans "Buscar" %}</button>
                </div>
            </div>
            <hr>
            <div class="contenedor-items">
                {% for tipo_producto in categorias %}
                    <div id="{{ tipo_producto.nombre }}">
                        <h2>{{ tipo_producto.nombre }}</h2>
                        {% for producto in restaurante.producto_set.all %}
                            {% if producto.idTipoProducto == tipo_producto %}
                            <div class="item">
                                <img src="{% static 'imagenes/' %}{{ producto.nombre|lower }}.png" alt="{{ producto.nombre }}" style="width: 70px; height: 70px;"class="img-item">
                                <div class="contenido-producto">
                                <h3 class="titulo-item">{{ producto.nombre }}</h3>
                                <p>{{ producto.descripcionProducto }}</p>
                                <p class="precio-item"><strong>{{ producto.precio }}€</strong></p>
                                </div>
                                <button class="boton-item">+</button>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <hr>
                {% endfor %}
            </div>
        </div>
        <div class="carrito" id="carrito">
            <div class="header-carrito">
                <h2>{% trans "Tu Carrito" %}</h2>
            </div>
            <div class="carrito-items">
            </div>
            <div class="carrito-total">
                <div class="fila">
                    <strong>{% trans "Tu Total" %}</strong>
                    <span class="carrito-precio-total">
                        0€
                    </span>
                </div>
                <button class="btn-pagar">{% trans "Pagar" %}</button>
            </div>
        </div>
    </div>
    <script>
        var currentUser = "{{ username }}"; 
    </script>
    <script>
        var currentUser = "{{ username }}";
        var idRestaurante = "{{ restaurante_id }}"; 
    </script>    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'js/producto.js' %}"></script>
{% endblock %}

AloTleDelisia/myapp/templates/myapp/usuario.html
{% extends 'base.html' %}
{% load i18n%}
{% block title %}Página de Usuario{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/usuario.css' %}">
<!-- <link rel="stylesheet" href="{% static 'css/chatbot.css' %}"> -->

<div class="user-container">
    <div class="user-profile">
        <div class="profile-section">
            <h2>{% trans "Hola:" %} {{usuario.first_name }} </h2>
        </div>
    </div>
    <div class="main-section">
        <div class="accordion">
            <button class="accordion-btn" onclick="toggleSection('mis-pedidos')"><b>{% trans "MIS PEDIDOS" %}</b></button>
            <!-- myapp/templates/myapp/usuario.html -->

<div class="content-section" id="mis-pedidos">
    <h3>{% trans "Mis Pedidos" %}</h3>
    <div class="wrapper">
        <div class="main">
            <div class="contenedor-items">
                {% for pedido in pedidos %}
                    <p>{% trans "Numero de pedido:" %} {{pedido.idPedido}}</p>
                    <p>{% trans "Importe:" %} {{ pedido.importePedido }}</p>
                    <hr>
                {% endfor %}
            </div>
        </div>
    </div>
</div>



            <button class="accordion-btn" onclick="toggleSection('preguntas-frecuentes')"><b>{% trans "PREGUNTAS FRECUENTES" %}</b></button>
            <div class="content-section" id="preguntas-frecuentes">
                <div class="preguntas">
                    <b>{% trans "¿Quiénes son los repartidores?" %}</b>
                    <p>{% trans "Los repartidores son mensajeros independientes conectados a nuestra plataforma. Son personas que disponen de tiempo libre, vehículo y smartphone propio, y buscan sacarle el máximo rendimiento ayudándote a resolver tus gestiones del modo más rápido y eficaz." %}</p>
                </div>
                <br>
                <div class="preguntas">
                    <b>{% trans "¿Cómo hago un pedido?" %}</b>
                    <p>{% trans "Para realizar un pedido en Alo Tle Delisia es muy sencillo. Sigue los siguientes pasos:" %}
                    <ol>
                        <li>{% trans "Elige el tipo de comida que quieres." %}</li>
                        <li>{% trans "Elige el restaurante que quieras." %}</li>
                        <li>{% trans "Añade los productos al carrito." %}</li>
                        <li>{% trans "Comprueba que tienes todo lo que quieres." %}</li>
                        <li>{% trans "Añade tu dirección y disfruta de la comida." %}</li>
                    </ol>
                    </p>
                </div>
                <br>

                <div class="preguntas">
                    <b>{% trans "¿Llega Alo Tle Delisia a mi barrio?" %}</b>
                    <p>{% trans "Alo Tle Delisia se asegura de indicar correctamente que restaurantes llegan a tu barrio." %}</p>
                </div>
                <br>

                <div class="preguntas">
                    <b>{% trans "¿Cuándo está abierto Alo Tle Delisia?" %}</b>
                    <p>{% trans "La mayoría de los restaurantes que trabajan con Alo Tle Delisia ofrecen servicio 24/7. No obstante, cada establecimiento tiene su propio horario, por lo que es posible que un establecimiento esté cerrado aunque Alo Tle Delisia esté disponible." %}</p>
                </div>
                <br>

                <div class="preguntas">
                    <b>{% trans "¿Qué puedo pedir?" %}</b>
                    <p>{% trans "Utiliza la app de Alo Tle Delisia para pedir cualquier producto cercano o hacer tus envíos exprés en la ciudad. Toda la comida china que te imagines esta disponible en nuestra app." %}</p>
                </div>
                <br>

                <div class="preguntas">
                    <b>{% trans "¿Qué tipo de vehículos utilizan los repartidores para la entrega? ¿Qué tamaño pueden tener mis pedidos?" %}</b>
                    <p>{% trans "Los repartidores registrados en la plataforma de Alo Tle Delisia utilizan distintos vehículos para transportar lo que quieras, siempre y cuando pese menos de 9 kg (el volumen de 3-4 bolsas de la compra) y quepa en una caja de 40x40x30 cm. Podrás pedir cualquier cosa que necesites teniendo en cuenta estas dimensiones." %}</p>
                </div>
                <br>

                <div class="preguntas">
                    <b>{% trans "¿Transportáis animales?" %}</b>
                    <p>{% trans "Nos encantaría poder ayudarte a trasladar a tu tortuga o tu serpiente, pero por ahora este tipo de servicio no está disponible. Esperamos que en un sea posible. Aunque en moto puede ser que se asusten un poco…" %}</p>
                </div>
                <br>

                <div class="preguntas">
                    <b>{% trans "¿Qué tipo de vehículos utilizan los repartidores para la entrega? ¿Qué tamaño pueden tener mis pedidos?" %}</b>
                    <p>{% trans "Los repartidores registrados en la plataforma de Alo Tle Delisia utilizan distintos vehículos para transportar lo que quieras, siempre y cuando pese menos de 9 kg (el volumen de 3-4 bolsas de la compra) y quepa en una caja de 40x40x30 cm. Podrás pedir cualquier cosa que necesites teniendo en cuenta estas dimensiones." %}</p>
                </div>
                <br>

                <div class="preguntas">
                    <b>{% trans "¿Qué tipo de vehículos utilizan los repartidores para la entrega? ¿Qué tamaño pueden tener mis pedidos?" %}</b>
                    <p>{% trans "Los repartidores registrados en la plataforma de Alo Tle Delisia utilizan distintos vehículos para transportar lo que quieras, siempre y cuando pese menos de 9 kg (el volumen de 3-4 bolsas de la compra) y quepa en una caja de 40x40x30 cm. Podrás pedir cualquier cosa que necesites teniendo en cuenta estas dimensiones." %}</p>
                </div>
                <br>

                <div class="preguntas">
                    <b>{% trans "¿Cómo puedo encontrar lo que busco?" %}</b>
                    <p>{% trans "En la parte superior de la pantalla, hay un buscador que te permitirá encontrar cualquier producto o establecimiento de la app en tu ciudad." %}</p>
                </div>
            </div>

            <button class="accordion-btn" onclick="toggleSection('danos-tu-opinion')"><b>{% trans "DANOS TU OPINION" %}</b></button>
            <div class="content-section" id="danos-tu-opinion">
                <link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css">

                <section id="demos" class="invisible">
                    <p><b>{% trans "POR FAVOR, INDIQUENOS SU EXPERIENCIA DE COMPRA:" %}
                        </b>
                    </p>
                    <label
                        class="mdc-text-field mdc-text-field--filled mdc-text-field--textarea mdc-text-field--no-label">
                        <span class="mdc-text-field__ripple"></span>
                        <span class="mdc-text-field__resizer">

                            <textarea id="input" class="mdc-text-field__input" rows="8" cols="40"
                                aria-label="Text Input"></textarea>
                        </span>
                        <span class="mdc-line-ripple"></span>
                    </label></br>
                    <button id="submit" class="mdc-button mdc-button--raised">
                        <span class="mdc-button__label">{% trans "ENVIAR" %}</span>
                    </button></br>

                    <p><b>{% trans "Detección de sentimientos:" %}</b></p>
                    <p id="output"></p>
                </section>
            </div>
            <script src="{% static 'js/usuario.js' %}"></script>
            <script type="module" src="{% static 'js/chatbot.js' %}"></script>
            <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
        </div>
    </div>
    </div>
    {% endblock %}